dustup/dustup

src/character.html.haml

the format is the same as special moves

add support for a follow_ups list to special moves

---

src/data/guilty_gear_xrd_rev_2/axl.yml
src/data/guilty_gear_xrd_rev_2/i-no.yml
src/data/guilty_gear_xrd_rev_2/leo.yml
src/data/guilty_gear_xrd_rev_2/may.yml
src/data/guilty_gear_xrd_rev_2/potemkin.yml

please make sure i didn't blow up any moves

follow_ups

---

src/data/guilty_gear_xrd_rev_2/answer.yml

I've not played with Answer any yet, so I think I've got his seal follow-ups right? But that'd definitely be something to check into before merging.

add answer for ggxrd-r2

---

src/data/guilty_gear_xrd_rev_2/jack-o.yml

Not particularly confident in this movelist. Haven't played with Jack-O either

add jack-o for ggxrd-r2

---

src/data/guilty_gear_xrd_rev_2/ramlethal.yml

add ramlethal valentine from guilty gear xrd rev 2

---

components/MoveSectionItem.js
data/games/guilty_gear_xrd_rev_2/movespecs/answer.json
data/games/guilty_gear_xrd_rev_2/movespecs/axl.json
data/games/guilty_gear_xrd_rev_2/movespecs/baiken.json
data/games/guilty_gear_xrd_rev_2/movespecs/bedman.json
data/games/guilty_gear_xrd_rev_2/movespecs/chipp.json
data/games/guilty_gear_xrd_rev_2/movespecs/elphelt.json
data/games/guilty_gear_xrd_rev_2/movespecs/faust.json
data/games/guilty_gear_xrd_rev_2/movespecs/i-no.json
data/games/guilty_gear_xrd_rev_2/movespecs/jack-o.json
data/games/guilty_gear_xrd_rev_2/movespecs/jam.json
data/games/guilty_gear_xrd_rev_2/movespecs/johnny.json
data/games/guilty_gear_xrd_rev_2/movespecs/leo.json
data/games/guilty_gear_xrd_rev_2/movespecs/may.json
data/games/guilty_gear_xrd_rev_2/movespecs/millia.json
data/games/guilty_gear_xrd_rev_2/movespecs/potemkin.json
data/games/guilty_gear_xrd_rev_2/movespecs/ramlethal.json
data/games/guilty_gear_xrd_rev_2/movespecs/sin.json
data/games/guilty_gear_xrd_rev_2/movespecs/slayer.json
data/games/guilty_gear_xrd_rev_2/movespecs/sol.json
data/games/under_night_in_birth_exe_late_st/movespecs/carmine.json
data/games/under_night_in_birth_exe_late_st/movespecs/enkidu.json
data/games/under_night_in_birth_exe_late_st/movespecs/hyde.json
data/games/under_night_in_birth_exe_late_st/movespecs/linne.json
data/games/under_night_in_birth_exe_late_st/movespecs/orie.json
data/games/under_night_in_birth_exe_late_st/movespecs/seth.json
movespec.schema.json

use followUps instead of follow_ups

---

components/MoveSectionItem.js

fix followUp notation

---

data/games/under_night_in_birth_exe_late_st/index.js
data/games/under_night_in_birth_exe_late_st/movespecs/chaos.json

add chaos from unist

---

data/games/under_night_in_birth_exe_late_st/index.js
data/games/under_night_in_birth_exe_late_st/movespecs/byakuya.json

add byakuya from unist

---

data/games/under_night_in_birth_exe_late_st/index.js
data/games/under_night_in_birth_exe_late_st/movespecs/hilda.json

add hilda from unist

---

data/games/under_night_in_birth_exe_late_st/index.js
data/games/under_night_in_birth_exe_late_st/movespecs/merkava.json

add merkava for unist

---

data/games/under_night_in_birth_exe_late_st/index.js
data/games/under_night_in_birth_exe_late_st/movespecs/nanase.json

add nanase from unist

---

data/games/under_night_in_birth_exe_late_st/index.js
data/games/under_night_in_birth_exe_late_st/movespecs/yuzuriha.json

add yuzuriha from unist

---

data/games/under_night_in_birth_exe_late_st/images/linne/2A.png
data/games/under_night_in_birth_exe_late_st/images/linne/2AA.png
data/games/under_night_in_birth_exe_late_st/images/linne/2B.png
data/games/under_night_in_birth_exe_late_st/images/linne/2C.png
data/games/under_night_in_birth_exe_late_st/images/linne/5A.png
data/games/under_night_in_birth_exe_late_st/images/linne/5B.png
data/games/under_night_in_birth_exe_late_st/images/linne/5C.png
data/games/under_night_in_birth_exe_late_st/images/linne/5CC.png
data/games/under_night_in_birth_exe_late_st/images/linne/66C.png
data/games/under_night_in_birth_exe_late_st/images/linne/6B.png
data/games/under_night_in_birth_exe_late_st/images/linne/Divine_Blaze.png
data/games/under_night_in_birth_exe_late_st/images/linne/Divine_Chains.png
data/games/under_night_in_birth_exe_late_st/images/linne/Elusive_Flash.png
data/games/under_night_in_birth_exe_late_st/images/linne/Flying_Swallow.png
data/games/under_night_in_birth_exe_late_st/images/linne/Moon_Gyre.png
data/games/under_night_in_birth_exe_late_st/images/linne/Sky_Fangs.png
data/games/under_night_in_birth_exe_late_st/images/linne/Tenacious_Mist.png
data/games/under_night_in_birth_exe_late_st/images/linne/The_Diviner.png
data/games/under_night_in_birth_exe_late_st/images/linne/Throw.png
data/games/under_night_in_birth_exe_late_st/images/linne/Veil_Off.png
data/games/under_night_in_birth_exe_late_st/images/linne/Wolf_Howl_1.png
data/games/under_night_in_birth_exe_late_st/images/linne/Wolf_Howl_2.png
data/games/under_night_in_birth_exe_late_st/images/linne/Wolf_Howl_3.png
data/games/under_night_in_birth_exe_late_st/images/linne/index.js
data/games/under_night_in_birth_exe_late_st/images/linne/j2B.png
data/games/under_night_in_birth_exe_late_st/images/linne/j6B.png
data/games/under_night_in_birth_exe_late_st/images/linne/jA.png
data/games/under_night_in_birth_exe_late_st/images/linne/jB.png
data/games/under_night_in_birth_exe_late_st/images/linne/jC.png
data/games/under_night_in_birth_exe_late_st/movespecs/linne.json

add images for linne from unist

---

data/games/under_night_in_birth_exe_late_st/movespecs/linne.json

fix linne's Wolf Howl rekkas

---

screens/CharacterListScreen.js
screens/GameListScreen.js
screens/MoveListScreen.js

android statusbar workaround

---

data/games/under_night_in_birth_exe_late_st/images/waldstein/1A.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/2A.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/2B.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/2C.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/3C.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/4B.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/5A.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/5B.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/5C.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/66B.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/6C.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/Durchbohren_A.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/Durchbohren_B.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/Eisen_Nagel.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/Ferzen_Volf.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/Guard_Thrust.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/Katastrophe.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/Sturmangriff.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/Throw.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/Veil_Off.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/Verderben.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/Werfen_Erschlagen.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/Wirbelwind.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/index.js
data/games/under_night_in_birth_exe_late_st/images/waldstein/j2C.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/j6C.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/jA.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/jB.png
data/games/under_night_in_birth_exe_late_st/images/waldstein/jC.png
data/games/under_night_in_birth_exe_late_st/movespecs/waldstein.json

add images for waldstein from unist

---

data/games/under_night_in_birth_exe_late_st/images/vatista/2A.png
data/games/under_night_in_birth_exe_late_st/images/vatista/2B.png
data/games/under_night_in_birth_exe_late_st/images/vatista/2BB.png
data/games/under_night_in_birth_exe_late_st/images/vatista/2C.png
data/games/under_night_in_birth_exe_late_st/images/vatista/5A.png
data/games/under_night_in_birth_exe_late_st/images/vatista/5B.png
data/games/under_night_in_birth_exe_late_st/images/vatista/5BB.png
data/games/under_night_in_birth_exe_late_st/images/vatista/5C.png
data/games/under_night_in_birth_exe_late_st/images/vatista/66B.png
data/games/under_night_in_birth_exe_late_st/images/vatista/Armabellum.png
data/games/under_night_in_birth_exe_late_st/images/vatista/Guard_Thrust.png
data/games/under_night_in_birth_exe_late_st/images/vatista/Lateus_Orbis.png
data/games/under_night_in_birth_exe_late_st/images/vatista/Leviosa.png
data/games/under_night_in_birth_exe_late_st/images/vatista/Luvel_Angelus.png
data/games/under_night_in_birth_exe_late_st/images/vatista/Mikoruseo.png
data/games/under_night_in_birth_exe_late_st/images/vatista/Stella_Lumen.png
data/games/under_night_in_birth_exe_late_st/images/vatista/Throw.png
data/games/under_night_in_birth_exe_late_st/images/vatista/Transvoranse.png
data/games/under_night_in_birth_exe_late_st/images/vatista/Veil_Off.png
data/games/under_night_in_birth_exe_late_st/images/vatista/Zahhishio.png
data/games/under_night_in_birth_exe_late_st/images/vatista/index.js
data/games/under_night_in_birth_exe_late_st/images/vatista/jA.png
data/games/under_night_in_birth_exe_late_st/images/vatista/jB.png
data/games/under_night_in_birth_exe_late_st/images/vatista/jC.png
data/games/under_night_in_birth_exe_late_st/movespecs/vatista.json

add images for vatista from unist

---

data/games/guilty_gear_xrd_rev_2/images/venom/2D.png
data/games/guilty_gear_xrd_rev_2/images/venom/2H.png
data/games/guilty_gear_xrd_rev_2/images/venom/2K.png
data/games/guilty_gear_xrd_rev_2/images/venom/2P.png
data/games/guilty_gear_xrd_rev_2/images/venom/2S.png
data/games/guilty_gear_xrd_rev_2/images/venom/5D.png
data/games/guilty_gear_xrd_rev_2/images/venom/5H.png
data/games/guilty_gear_xrd_rev_2/images/venom/5K.png
data/games/guilty_gear_xrd_rev_2/images/venom/5P.png
data/games/guilty_gear_xrd_rev_2/images/venom/6H.png
data/games/guilty_gear_xrd_rev_2/images/venom/6P.png
data/games/guilty_gear_xrd_rev_2/images/venom/ball_set.png
data/games/guilty_gear_xrd_rev_2/images/venom/bishop_runout.png
data/games/guilty_gear_xrd_rev_2/images/venom/c_S.png
data/games/guilty_gear_xrd_rev_2/images/venom/carcass_raid.png
data/games/guilty_gear_xrd_rev_2/images/venom/dark_angel.png
data/games/guilty_gear_xrd_rev_2/images/venom/double_head_morbid.png
data/games/guilty_gear_xrd_rev_2/images/venom/f_S.png
data/games/guilty_gear_xrd_rev_2/images/venom/index.js
data/games/guilty_gear_xrd_rev_2/images/venom/j_D.png
data/games/guilty_gear_xrd_rev_2/images/venom/j_H.png
data/games/guilty_gear_xrd_rev_2/images/venom/j_K.png
data/games/guilty_gear_xrd_rev_2/images/venom/j_P.png
data/games/guilty_gear_xrd_rev_2/images/venom/j_S.png
data/games/guilty_gear_xrd_rev_2/images/venom/mad_struggle.png
data/games/guilty_gear_xrd_rev_2/images/venom/qv.png
data/games/guilty_gear_xrd_rev_2/images/venom/red_hail.png
data/games/guilty_gear_xrd_rev_2/images/venom/stinger_aim.png
data/games/guilty_gear_xrd_rev_2/images/venom/teleport.png
data/games/guilty_gear_xrd_rev_2/movespecs/venom.json

GGXrd-R2 images - venom

---

package-lock.json

j/k this will remediate CVE-2018-16469

upgrade the merge package

---

app.json
data/launcher.png
data/launcher_foreground.png

this adds a launcher icon for iOS and an adaptive launcher for android

add launcher icon
